# Generated by Django 4.2.4 on 2023-08-31 12:34

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='document',
            field=models.FileField(default=1, upload_to='content-documents/', validators=[content.models.Content.validate_pdf_extension]),
            preserve_default=False,
        ),
    ]
